name: bot

on:
    push:

jobs:
    BOT:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install geckodriver
              run: |
                sudo apt-get update
                sudo apt-get install -y firefox
                sudo apt-get install -y wget
                wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
                tar -xzf geckodriver-v0.36.0-linux64.tar.gz
                sudo mv geckodriver /usr/bin/
                sudo chmod +x /usr/bin/geckodriver

            - name: Install requirements
              run: |
                pip install -r requirements.txt || { echo 'Ошибка при установке зависимостей'; exit 1; }

            - name: Run app
              run: |
                ulimit -v 4000000  # Устанавливаем лимит виртуальной памяти (можно отрегулировать по необходимости)
                python проход.py || { echo 'Программа завершилась с ошибкой'; exit 1; }

